name: CI Build

on:
  push:
    branches: [ main ]
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      - name: Restore Tools
        shell: bash
        run: |
          dotnet tool restore
      - name: Run the Cake script
        uses: cake-build/cake-action@v1
        with:
          target: Default
          verbosity: Verbose
          cake-version: 1.1.0
        env:
          NUGET_TOKEN: ${{secrets.NUGET_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v1
        name: Upload Artifacts
        with:
          name: us-package
          path: dist/package/
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Install the package from NuGet or download the `nupkg` directly below.
          files: |
            ./dist/package/*.nupkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}